config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :products
  get '/search' => 'products#search'
  root 'products#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string
#  desc        :text
#  category_id :integer
#  image       :string
#  price       :integer
#  published   :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Product < ActiveRecord::Base
  searchkick searchable: [:name, :desc, :category_name],
             suggest: [:name],
             highlight: [:name, :desc],
             synonyms: [["apple", "蘋果"], ["asus", "華碩"]]

  belongs_to :category

  scope :search_import, -> { includes(:category) }

  def search_data
    {
      name: name,
      category_name: category.name,
      desc: desc
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_start_time

  def set_start_time
    @start_time = Time.now.to_f
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.order('created_at DESC').page(params[:page]).per(10)
  end

  def search
    search_params = { page: params[:page],
                      per_page: 10,
                      suggest: true,
                      highlight: { tag: "<mark>" },
                      aggs: [:category_name]
                    }
    search_params.merge!(where: { category_name: params[:cn] }) if params[:cn].present?
    @products = Product.search(params[:q], search_params)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :desc, :category_id, :image, :price, :published)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.slim
= form_for(@category, html: { class: "form-horizontal", role: "form" }) do |f|
  - if @category.errors.any?
    .alert.alert-danger.alert-dismissable role="alert"
      button.close type="button" data-dismiss="alert"
        span aria-hidden="true"
          | &times;
        span.sr-only
          | Close
      h4= "#{pluralize(@category.errors.count,"error")} prohibited this category from being saved:"
      ul
        - @category.errors.full_messages.each do |msg|
          li= msg
  .form-group
    = f.label :name, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :name, class: "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"

app/views/categories/edit.html.slim
.page-header
  = link_to categories_path, class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to @category, class: 'btn btn-primary' do
    span.glyphicon.glyphicon-info-sign
    |  Show 
  h1
    | Editing 
    | category

= render 'form'

app/views/categories/index.html.slim
.page-header
  = link_to new_category_path, class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-plus
    |  New Category
  h1
    | Listing categories

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th
          | Name
        th
        th
        th
    tbody
      - @categories.each do | category |
        tr
          td
            = category.name
          td
            = link_to 'Show', category
          td
            = link_to 'Edit', edit_category_path(category) 
          td
            = link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } 

app/views/categories/new.html.slim
.page-header
  = link_to categories_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  h1
    | New 
    | category

= render 'form'

app/views/categories/show.html.slim
.page-header
  = link_to categories_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to edit_category_path(@category), class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-pencil
    |  Edit 
  h1
    | Show category
dl.dl-horizontal
  dt
    | Name:
  dd
    = @category.name

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    meta name="description" content=""
    meta name="author" content=""
    title
      | Searchkick Example
    /! HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-inverse.navbar-fixed-top role="navigation"
      .container
        .navbar-header
          button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
            span.sr-only
              | Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to "Searchkick Example", root_path, class: "navbar-brand"
        #navbar.collapse.navbar-collapse
          .pull-right
            span Page Rendered in #{sprintf('%.3f', (Time.now.to_f - @start_time) )} seconds
          ul.nav.navbar-nav
            li = link_to 'Products', products_path
            li = link_to 'Categories', categories_path
    .container
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
          button.close type="button" data-dismiss="alert"
            span aria-hidden="true"
              | &times;
            span.sr-only
              | Close
          = msg
      = yield

app/views/products/_form.html.slim
= form_for(@product, html: { class: "form-horizontal", role: "form" }) do |f|
  - if @product.errors.any?
    .alert.alert-danger.alert-dismissable role="alert"
      button.close type="button" data-dismiss="alert"
        span aria-hidden="true"
          | &times;
        span.sr-only
          | Close
      h4= "#{pluralize(@product.errors.count,"error")} prohibited this product from being saved:"
      ul
        - @product.errors.full_messages.each do |msg|
          li= msg
  .form-group
    = f.label :name, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :name, class: "form-control"
  .form-group
    = f.label :desc, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :desc, class: "form-control"
  .form-group
    = f.label :category_id, class: "col-sm-2 control-label"
    .col-sm-10
      = f.collection_select :category_id, Category.all, :id, :name, { prompt: true }, { class: "form-control" }
  .form-group
    = f.label :image, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :image, class: "form-control"
  .form-group
    = f.label :price, class: "col-sm-2 control-label"
    .col-sm-10
      = f.number_field :price, class: "form-control"
  .form-group
    = f.label :published, class: "col-sm-2 control-label"
    .col-sm-10
      = f.check_box :published, class: "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"

app/views/products/_search_form.slim
.row
  .col-md-12
    form action='/search' method='get'
      .input-group
        span class="input-group-addon" id="search"
          span class="glyphicon glyphicon-search" aria-hidden="true"
        input type="search" class="form-control" placeholder="Search.." aria-describedby="search" name="q" value=(params[:q] if params[:q].present?)
    - if products.try(:suggestions).present?
      | 你是要搜尋?：
      = products.suggestions.map{ |s| link_to s, search_path(q: s) }.join(', ').html_safe

app/views/products/edit.html.slim
.page-header
  = link_to products_path, class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to @product, class: 'btn btn-primary' do
    span.glyphicon.glyphicon-info-sign
    |  Show 
  h1
    | Editing 
    | product

= render 'form'

app/views/products/index.html.slim
.page-header
  = link_to new_product_path, class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-plus
    |  New Product
  h1
    | Listing products

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th
          | Name
        th
          | Desc
        th
          | Category
        th
          | Image
        th
          | Price
        th
          | Published
        th
        th
        th
    tbody
      - @products.each do | product |
        tr
          td
            = product.name
          td
            = product.desc
          td
            = product.category_id
          td
            = product.image
          td
            = product.price
          td
            = product.published
          td
            = link_to 'Show', product
          td
            = link_to 'Edit', edit_product_path(product) 
          td
            = link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } 

app/views/products/new.html.slim
.page-header
  = link_to products_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  h1
    | New 
    | product

= render 'form'

app/views/products/search.slim
.page-header
  = link_to new_product_path, class: 'btn btn-primary' do
    span.glyphicon.glyphicon-plus
    |  New Product
  h1
    | Listing products

= render 'search_form', products: @products

div style="margin-top: 50px;"
.row
  - is_aggs = @products.try(:aggs).present?
  - if is_aggs
    .col-md-2
      | Category
      ul
        - @products.aggs['category_name']['buckets'].each do |agg|
          - cn = agg['key']
          li
            = link_to cn, search_path(q: params[:q], cn: cn)
            = "(#{agg['doc_count']})"

  div class=(is_aggs ? '.col-md-10' : '.col-md-12')
    .table-responsive
      table.table.table-striped.table-bordered.table-hover
        thead
          tr
            th
              | ID
            th
              | Name
            th
              | Desc
            th
              | Category
            th
              | Price
            th
              | Published
            th
            th
            th
        tbody
          /- @products.each do | product |
          - @products.with_details.each do |product, _|
            - highlight = _[:highlight] || {}
            tr
              td = product.id
              td
                = highlight[:name].try(:html_safe) || product.name
              td
                = highlight[:desc].try(:html_safe) || product.desc
              td
                = product.category.name
              td
                = product.price
              td
                = product.published
              td
                = link_to 'Show', product
              td
                = link_to 'Edit', edit_product_path(product)
              td
                = link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }
    | Total: #{@products.total_count}
    br
    = paginate @products, theme: 'twitter-bootstrap-3'

app/views/products/show.html.slim
.page-header
  = link_to products_path, class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back
  = link_to edit_product_path(@product), class: 'btn btn-primary' do
    span.glyphicon.glyphicon-pencil
    |  Edit
  h1
    | Show product
dl.dl-horizontal
  dt
    | Name:
  dd
    = @product.name
  dt
    | Desc:
  dd
    = @product.desc
  dt
    | Category:
  dd
    = @product.category.name
  dt
    | Image:
  dd
    = @product.image
  dt
    | Price:
  dd
    = @product.price
  dt
    | Published:
  dd
    = @product.published